"""phase 1 initial schema: users, sets, cards, collection_items

Revision ID: 9442463364c2
Revises: 
Create Date: 2026-07-13 11:33:58.245459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9442463364c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('printed_total', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('symbol_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_name'), 'sets', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('supertype', sa.String(length=32), nullable=True),
    sa.Column('subtypes', sa.JSON(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('image_small_url', sa.String(length=512), nullable=True),
    sa.Column('image_large_url', sa.String(length=512), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_rarity'), 'cards', ['rarity'], unique=False)
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    op.create_index(op.f('ix_cards_supertype'), 'cards', ['supertype'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('condition', sa.Enum('mint', 'near_mint', 'excellent', 'good', 'played', 'poor', name='card_condition'), server_default='near_mint', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'condition', name='uq_collection_user_card_cond')
    )
    op.create_index(op.f('ix_collection_items_card_id'), 'collection_items', ['card_id'], unique=False)
    op.create_index(op.f('ix_collection_items_user_id'), 'collection_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_user_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_card_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_cards_supertype'), table_name='cards')
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_rarity'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sets_name'), table_name='sets')
    op.drop_table('sets')
    # ### end Alembic commands ###
