"""phase 3: prices table

Revision ID: b3a30871e156
Revises: 9442463364c2
Create Date: 2026-07-13 16:52:16.321358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a30871e156'
down_revision: Union[str, Sequence[str], None] = '9442463364c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'source', 'variant', 'date', name='uq_prices_card_source_variant_date')
    )
    op.create_index('ix_prices_card_date', 'prices', ['card_id', 'date'], unique=False)
    op.create_index(op.f('ix_prices_card_id'), 'prices', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_card_id'), table_name='prices')
    op.drop_index('ix_prices_card_date', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
